name: Deploy to Maven Central

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  deploy:
    if: github.head_ref == 'develop' || startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Determine version from branch
        id: version
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Source branch: $BRANCH_NAME"
          
          # Set version based on branch name
          if [[ "$BRANCH_NAME" =~ ^release/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "Release branch detected, version: $VERSION"
          elif [[ "$BRANCH_NAME" == "main" ]]; then
            VERSION="1.2.1"
            echo "Main branch detected, using base version: $VERSION"
          else
            SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9]/-/g')
            VERSION="1.2.1-${SANITIZED_BRANCH}-SNAPSHOT"
            echo "Feature branch detected, version: $VERSION"
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Final version: $VERSION"

      - name: Debug environment variables
        run: |
          echo "Maven Username present: ${{ secrets.MAVEN_USERNAME != '' }}"
          echo "Maven Password present: ${{ secrets.MAVEN_PASSWORD != '' }}"
          echo "GPG Key present: ${{ secrets.MAVEN_GPG_PRIVATE_KEY != '' }}"
          echo "GPG Passphrase present: ${{ secrets.MAVEN_GPG_PASSPHRASE != '' }}"
          echo "Version: ${{ steps.version.outputs.version }}"
      - run: sed -i "s/\"1.3.0\"/\"${{ steps.version.outputs.version }}\"/g" gradle-plugin/src/main/kotlin/net/kigawa/renlin/RenlinCompilerPlugin.kt
      - name: Publish package
        run: >
          ./gradlew
          -PmavenCentralUsername=${{ secrets.MAVEN_USERNAME }}
          -PmavenCentralPassword=${{ secrets.MAVEN_PASSWORD }}
          -PsigningInMemoryKeyId=${{ secrets.MAVEN_GPG_KEY_ID }}
          -PsigningInMemoryPassword=${{ secrets.MAVEN_GPG_PASSPHRASE }}
          :gradle-plugin:publishAndReleaseToMavenCentral
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Auto-merge PR on successful deployment
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (pr) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'merge'
              });
              console.log(`PR #${pr.number} has been automatically merged after successful deployment`);
            }